services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - class_journal

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - class_journal

volumes:
  postgres:

networks:
  class_journal:
    driver: bridge